### ISSUE TITLE
[COMPLETE(?) - see comments] Required Feature: OrderId - random generator in schema

### ISSUE THREAD

**Issue by mewing0328** [leeclaire156/Produce-Pal#130]
1. Add defaults of random # generator
2. Make required
3. Updated order seeds with the same since it will be required type
4. Unique

**Comment by leeclaire156** [comment]
completed generator.

### Fair warning:
1. did not add defaults (what defaults were I suppose to add? .w. )
2. did not make required on model, cause they will generate with every order upon order creation when passing product, seller info, etc on `success.js` page. 
3. made the orderID a `string` because that's what the model said the orderId would be, BUT I did only use (whole) numbers so if you want to change the model, typeDef, mutations, etc from `String` to `Int`, I can change the orderId to `INT` as well. Just let me know.
4. Up to 10,000 unique orderIds can be made site-wide per day, for our purposes I felt that this number was enough.

**Comment by mewing0328** [comment]
Makes total sense.  We don't need required anymore because I manually added the orderId to the seeds.

If they are being generated in the success page at order creation then we don't need required on the model.

No, let's keep it to string! For some reason, it didn't like Int earlier this week and the only way I could debug was changing productId and orderId to String.

Everything else sounds good. Go ahead and mark this complete.  Thank you!!!
